//
//  AllItems.swift
//  xiv-turnins
//
//  Created by Jared on 3/21/23.
//

// List of possible items, populated using BeautifulSoup to scrape the wiki.

let allItems: Set<String> = [
    // Alchemist Items
    "Antidote",
    "Archaeoskin Codex",
    "Archaeoskin Grimoire",
    "Ash Picatrix",
    "Ash Wand",
    "Beetle Glue",
    "Blinding Potion",
    "Bluespirit Codex",
    "Bluespirit Grimoire",
    "Book of Aurum Regis",
    "Book of Mythril",
    "Book of Silver",
    "Budding Ash Wand",
    "Budding Maple Wand",
    "Budding Oak Wand",
    "Budding Rosewood Wand",
    "Budding Yew Wand",
    "Commanding Craftsman's Draught",
    "Commanding Craftsman's Tea",
    "Competent Craftsman's Draught",
    "Competent Craftsman's Syrup",
    "Competent Craftsman's Tea",
    "Cunning Craftsman's Draught",
    "Cunning Craftsman's Syrup",
    "Cunning Craftsman's Tea",
    "Dhalmelskin Codex",
    "Dhalmelskin Grimoire",
    "Draconian Potion of Dexterity",
    "Draconian Potion of Intelligence",
    "Draconian Potion of Mind",
    "Draconian Potion of Vitality",
    "Dragonskin Codex",
    "Dragonskin Grimoire",
    "Dwarven Mythril Codex",
    "Dwarven Mythril Grimoire",
    "Echo Drops",
    "Embossed Book of Electrum",
    "Embossed Book of Silver",
    "Enchanted Dimythrite Ink",
    "Enchanted High Durium Ink",
    "Enchanted Manasilver Ink",
    "Enchanted Manganese Ink",
    "Engraved Goatskin Grimoire",
    "Engraved Hard Leather Grimoire",
    "Engraved Leather Grimoire",
    "Ether",
    "Eye Drops",
    "Gaja Codex",
    "Gaja Grimoire",
    "Gazelleskin Codex",
    "Gazelleskin Grimoire",
    "Goatskin Grimoire",
    "Gold Needle",
    "Grade 1 Dexterity Dissolvent",
    "Grade 1 Intelligence Alkahest",
    "Grade 1 Mind Dissolvent",
    "Grade 1 Reisui of Dexterity",
    "Grade 1 Reisui of Mind",
    "Grade 1 Reisui of Vitality",
    "Grade 1 Strength Alkahest",
    "Grade 1 Strength Dissolvent",
    "Grade 1 Vitality Alkahest",
    "Grade 1 Vitality Dissolvent",
    "Grade 5 Mind Alkahest",
    "Grade 5 Strength Alkahest",
    "Grade 5 Tincture of Dexterity",
    "Grade 5 Tincture of Intelligence",
    "Grade 5 Tincture of Mind",
    "Grade 5 Tincture of Strength",
    "Grade 5 Tincture of Vitality",
    "Grade 5 Vitality Alkahest",
    "Growth Formula Iota",
    "Growth Formula Kappa",
    "Growth Formula Theta",
    "Gyuki Leather Codex",
    "Gyuki Leather Grimoire",
    "Hallowed Chestnut Wand",
    "Hard Leather Grimoire",
    "Hi-Ether",
    "Hi-Potion",
    "Hi-Potion of Dexterity",
    "Hi-Potion of Intelligence",
    "Hi-Potion of Mind",
    "Hi-Potion of Strength",
    "Hi-Potion of Vitality",
    "Holy Cedar Wand",
    "Infusion of Dexterity",
    "Infusion of Intelligence",
    "Infusion of Mind",
    "Infusion of Strength",
    "Infusion of Vitality",
    "Koppranickel Codex",
    "Koppranickel Index",
    "Kumbhiraskin Codex",
    "Kumbhiraskin Grimoire",
    "Leather Grimoire",
    "Luncheon Toadskin Codex",
    "Luncheon Toadskin Grimoire",
    "Maple Picatrix",
    "Maple Wand",
    "Marid Leather Codex",
    "Marid Leather Grimoire",
    "Mega-Potion",
    "Mega-Potion of Dexterity",
    "Mega-Potion of Intelligence",
    "Mega-Potion of Mind",
    "Mega-Potion of Strength",
    "Mega-Potion of Vitality",
    "Moon Gel",
    "Noble's Codex",
    "Noble's Picatrix",
    "Ophiotauroskin Magitek Codex",
    "Ophiotauroskin Magitek Index",
    "Paralyzing Potion",
    "Poisoning Potion",
    "Potent Blinding Potion",
    "Potent Paralyzing Potion",
    "Potent Poisoning Potion",
    "Potent Sleeping Potion",
    "Potent Spiritbond Potion",
    "Potion",
    "Potion of Dexterity",
    "Potion of Intelligence",
    "Potion of Mind",
    "Potion of Strength",
    "Potion of Vitality",
    "Refined Natron",
    "Saigaskin Codex",
    "Saigaskin Grimoire",
    "Silencing Potion",
    "Sleeping Potion",
    "Smelling Salts",
    "Spine Drops",
    "Starch Glue",
    "Sungold Firesand",
    "Superior Spiritbond Potion",
    "Tane Mahuta",
    "Tigerskin Codex",
    "Tigerskin Grimoire",
    "Tincture of Dexterity",
    "Tincture of Intelligence",
    "Tincture of Mind",
    "Tincture of Strength",
    "Tincture of Vitality",
    "Wand of Frost",
    "Wand of Gales",
    "Wand of Tides",
    "Wand of Tremors",
    "Weak Blinding Potion",
    "Weak Poisoning Potion",
    "Weak Silencing Potion",
    "Whispering Ash Wand",
    "Whispering Maple Wand",
    "Wyvernskin Codex",
    "Wyvernskin Grimoire",
    "Yew Picatrix",
    "Yew Wand",
    "Zonureskin Codex",
    "Zonureskin Grimoire",
    
    // Armorer Items
    "Adamantite Armor of Fending",
    "Adamantite Chain Hose of Maiming",
    "Adamantite Gauntlets of Fending",
    "Adamantite Helm of Maiming",
    "Adamantite Mail of Maiming",
    "Adamantite Sabatons of Maiming",
    "Adamantite Scutum",
    "Amateur's Alembic",
    "Amateur's Skillet",
    "Aurum Regis Sollerets of Healing",
    "Bismuth Bracelet of Casting",
    "Bismuth Bracelet of Healing",
    "Bismuth Fat Cat Frypan",
    "Bismuth Goggles of Fending",
    "Bismuth Headgear of Maiming",
    "Bismuth Ring of Aiming",
    "Bladed Lantern Shield",
    "Bluespirit Cuirass of Fending",
    "Bluespirit Gauntlets of Maiming",
    "Bluespirit Headgear of Casting",
    "Bluespirit Porxie Frypan",
    "Bluespirit Sabatons of Maiming",
    "Bluespirit Tower Shield",
    "Bomb Frypan",
    "Brass Alembic",
    "Bronze Alembic",
    "Bronze Barbut",
    "Bronze Buckler",
    "Bronze Celata",
    "Bronze Chain Coif",
    "Bronze Cuirass",
    "Bronze Gauntlets",
    "Bronze Haubergeon",
    "Bronze Hoplon",
    "Bronze Mitt Gauntlets",
    "Bronze Sabatons",
    "Bronze Sallet",
    "Bronze Scutum",
    "Bronze Skillet",
    "Bronze Sollerets",
    "Bull Hoplon",
    "Chondrite Alembic",
    "Chondrite Bomb Frypan",
    "Chondrite Gloves of Aiming",
    "Chondrite Gloves of Healing",
    "Chondrite Gloves of Maiming",
    "Chondrite Magitek Shield",
    "Chondrite Sollerets of Scouting",
    "Chondrite Top of Fending",
    "Cobalt Barbut",
    "Cobalt Bladed Lantern Shield",
    "Cobalt Haubergeon",
    "Cobalt Mesail",
    "Cobalt Mitt Gauntlets",
    "Cobalt Sallet",
    "Cobalt Scutum",
    "Cobalt Skillet",
    "Cobalt-plated Caligae",
    "Cobalt-plated Jackboots",
    "Conical Alembic",
    "Decorated Bronze Barbut",
    "Decorated Bronze Mitt Gauntlets",
    "Decorated Buckler",
    "Deepgold Alembic",
    "Deepgold Gauntlets of Fending",
    "Deepgold Gauntlets of Maiming",
    "Deepgold Mail of Fending",
    "Deepgold Mask of Scouting",
    "Deepgold Shield",
    "Deepgold Sollerets of Maiming",
    "Deepgold Surcoat of Maiming",
    "Deepgold Wings of Fending",
    "Doman Iron Alembic",
    "Doman Iron Gauntlets of Fending",
    "Doman Iron Gauntlets of Maiming",
    "Doman Iron Greaves of Fending",
    "Doman Iron Kite Shield",
    "Doman Steel Armet of Maiming",
    "Doman Steel Frypan Caliente",
    "Doman Steel Gauntlets of Maiming",
    "Doman Steel Gauntlets of Scouting",
    "Doman Steel Greaves of Striking",
    "Doman Steel Tabard of Fending",
    "Dwarven Mythril Alembic",
    "Dwarven Mythril Chainmail of Maiming",
    "Dwarven Mythril Frypan",
    "Dwarven Mythril Helm of Striking",
    "Dwarven Mythril Shield",
    "Dwarven Mythril Shoes of Fending",
    "Frypan Caliente",
    "Hardsilver Alembic",
    "Heavy Adamantite Gauntlets of Fending",
    "Heavy Iron Armor",
    "Heavy Iron Flanchard",
    "Heavy Iron Gauntlets",
    "Heavy Steel Armor",
    "Heavy Steel Flanchard",
    "Heavy Steel Gauntlets",
    "Hells' Kitchen",
    "High Durium Alembic",
    "High Durium Armguards of Aiming",
    "High Durium Armor of Fending",
    "High Durium Armor of Maiming",
    "High Durium Gauntlets of Maiming",
    "High Durium Kite Shield",
    "High Durium Shield",
    "High Durium Sollerets of Fending",
    "High Durium Sollerets of Maiming",
    "High Mythril Armor",
    "High Mythril Flanchard",
    "High Steel Armguards of Maiming",
    "High Steel Barbut of Fending",
    "High Steel Barbut of Maiming",
    "High Steel Bomb Frypan",
    "High Steel Gauntlets of Fending",
    "High Steel Helm of Fending",
    "High Steel Mail of Fending",
    "High Steel Scutum",
    "High Steel Sollerets of Maiming",
    "Horn Scale Fingers",
    "Horn Scale Mail",
    "Initiate's Alembic",
    "Initiate's Skillet",
    "Iron Alembic",
    "Iron Celata",
    "Iron Cuirass",
    "Iron Elmo",
    "Iron Frypan",
    "Iron Gauntlets",
    "Iron Hoplon",
    "Iron Kite Shield",
    "Iron Lantern Shield",
    "Iron Sabatons",
    "Iron Sallet",
    "Iron Scale Mail",
    "Iron Scutum",
    "Iron Skillet",
    "Iron Vambraces",
    "Iron-plated Jackboots",
    "Mandragoras Frypan",
    "Manganese Alembic",
    "Manganese Armor of the Behemoth King",
    "Manganese Armor of the Behemoth Queen",
    "Manganese Gaiters of the Falling Dragon",
    "Manganese Gauntlets of the Behemoth Queen",
    "Manganese Helm of the Behemoth King",
    "Molybdenum Alembic",
    "Molybdenum Armguards of Scouting",
    "Molybdenum Frypan",
    "Molybdenum Greaves of Fending",
    "Molybdenum Headgear of Fending",
    "Molybdenum Headgear of Maiming",
    "Molybdenum Kite Shield",
    "Mythril Alembic",
    "Mythril Barbut",
    "Mythril Celata",
    "Mythril Chain Coif",
    "Mythril Cuirass",
    "Mythril Elmo",
    "Mythril Gauntlets",
    "Mythril Mesail",
    "Mythril Mitt Gauntlets",
    "Mythril Sabatons",
    "Mythril Vambraces",
    "Mythril-plated Caligae",
    "Mythril-plated Jackboots",
    "Mythrite Alembic",
    "Mythrite Bladed Lantern Shield",
    "Mythrite Gauntlets of Fending",
    "Mythrite Hauberk of Maiming",
    "Mythrite Sallet of Maiming",
    "Reinforced Iron Sallet",
    "Reinforced Mythril Elmo",
    "Silver Alembic",
    "Steel Alembic",
    "Steel Barbut",
    "Steel Celata",
    "Steel Chainmail",
    "Steel Elmo",
    "Steel Frypan",
    "Steel Gauntlets",
    "Steel Mitt Gauntlets",
    "Steel Sabatons",
    "Steel Sallet",
    "Steel Scale Fingers",
    "Steel Scale Greaves",
    "Steel Scale Mail",
    "Steel Skillet",
    "Steel Vambraces",
    "Tigerskin Coat of Fending",
    "Titanbronze Alembic",
    "Titanbronze Headband of Scouting",
    "Titanbronze Moogle Frypan",
    "Titanbronze Tower Shield",
    "Titanium Headgear of Scouting",
    "Titanium Helm of Fending",
    "Titanium Kite Shield",
    "Titanium Mail of Fending",
    "Titanium Mail of Striking",
    "Titanium Mask of Aiming",
    "Titanium Sabatons of Fending",
    "Titanium Sabatons of Maiming",
    "Titanium Sallet of Maiming",
    "Titanium Vambraces of Maiming",
    "Tortoiseshell Scale Fingers",
    "Tortoiseshell Scale Mail",
    "White Skillet",
    
    // Blacksmith Items
    "Adamantite Bill",
    "Adamantite Broadsword",
    "Adamantite Culinary Knife",
    "Adamantite Dolabra",
    "Adamantite Greatsword",
    "Adamantite Knives",
    "Adamantite Knuckles",
    "Adamantite Mortar",
    "Adamantite Scythe",
    "Amateur's Awl",
    "Amateur's Claw Hammer",
    "Amateur's Cross-pein Hammer",
    "Amateur's Culinary Knife",
    "Amateur's Doming Hammer",
    "Amateur's File",
    "Amateur's Hatchet",
    "Amateur's Head Knife",
    "Amateur's Mortar",
    "Amateur's Pliers",
    "Bas-relief Cobalt Saw",
    "Bas-relief Iron Saw",
    "Birdsbeak Hammer",
    "Bismuth Bow",
    "Bismuth Culinary Knife",
    "Bismuth Greatsword",
    "Bismuth Gunblade",
    "Bismuth Lapidary Hammer",
    "Bismuth Saw",
    "Bluespirit Handgonne",
    "Bluespirit Mortar",
    "Bluespirit Pickaxe",
    "Bluespirit Raising Hammer",
    "Bluespirit Round Knife",
    "Bluespirit Sword",
    "Brass Bastard Sword",
    "Brass Hatchet",
    "Brass Head Knife",
    "Brass Knuckles",
    "Brass Viking Sword",
    "Bronze Awl",
    "Bronze Bastard Sword",
    "Bronze Chaser Hammer",
    "Bronze Claw Hammer",
    "Bronze Cross-pein Hammer",
    "Bronze Culinary Knife",
    "Bronze Doming Hammer",
    "Bronze File",
    "Bronze Hatchet",
    "Bronze Head Knife",
    "Bronze Knuckles",
    "Bronze Labrys",
    "Bronze Mortar",
    "Bronze Pickaxe",
    "Bronze Raising Hammer",
    "Bronze Saw",
    "Bronze Sledgehammer",
    "Bronze Spatha",
    "Bronze War Axe",
    "Chondrite Claw Hammer",
    "Chondrite Cross-pein Hammer",
    "Chondrite Hatchet",
    "Chondrite Magitek Baghnakhs",
    "Chondrite Magitek Samurai Blade",
    "Chondrite Magitek War Scythe",
    "Chondrite Mortar",
    "Chondrite Raising Hammer",
    "Chondrite Sledgehammer",
    "Cloud Axe",
    "Cobalt Awl",
    "Cobalt Claw Hammer",
    "Cobalt Claws",
    "Cobalt Dolabra",
    "Cobalt File",
    "Cobalt Hatchet",
    "Cobalt Knuckles",
    "Cobalt Mortar",
    "Cobalt Raising Hammer",
    "Cobalt Shamshir",
    "Cobalt Sledgehammer",
    "Cobalt Winglet",
    "Crowsbeak Hammer",
    "Deepgold Arquebus",
    "Deepgold Bayonet",
    "Deepgold Chakrams",
    "Deepgold Claw Hammer",
    "Deepgold Daggers",
    "Deepgold File",
    "Deepgold Raising Hammer",
    "Deepgold Sword",
    "Deepgold Uchigatana",
    "Demilune Bhuj",
    "Doman Iron Claw Hammer",
    "Doman Iron Culinary Knife",
    "Doman Iron Daggers",
    "Doman Iron Longsword",
    "Doman Iron Pickaxe",
    "Doman Iron Raising Hammer",
    "Doman Steel Battleaxe",
    "Doman Steel File",
    "Doman Steel Mortar",
    "Doman Steel Round Knife",
    "Doman Steel-barreled Musketoon",
    "Dwarven Mythril Claw Hammer",
    "Dwarven Mythril Culinary Knife",
    "Dwarven Mythril Glaives",
    "Dwarven Mythril Lapidary Hammer",
    "Dwarven Mythril Pickaxe",
    "Dwarven Mythril Planisphere",
    "Dwarven Mythril Pliers",
    "Dwarven Mythril Rotaries",
    "Dwarven Mythril Round Knife",
    "Egret Dolabra",
    "Electrum Head Knife",
    "Electrum Lapidary Hammer",
    "Folded High Steel Greatsword",
    "Hardsilver Round Knife",
    "Hardsilver Saw",
    "Hardsilver Texture Hammer",
    "High Durium Bhuj",
    "High Durium Cesti",
    "High Durium Cross-pein Hammer",
    "High Durium Glaives",
    "High Durium Musketoon",
    "High Durium Pickaxe",
    "High Durium Sword",
    "High Durium Uchigatana",
    "High Durium War Scythe",
    "High Steel Cross-pein Hammer",
    "High Steel Culverin",
    "High Steel Mortar",
    "High Steel Pliers",
    "High Steel Saw",
    "High Steel Scythe",
    "High Steel Uchigatana",
    "High Steel-barreled Snaphance",
    "Horned Hatchet",
    "Inferno Axe",
    "Initiate's Awl",
    "Initiate's Culinary Knife",
    "Initiate's File",
    "Initiate's Hatchet",
    "Initiate's Pliers",
    "Initiate's Saw",
    "Initiate's Scythe",
    "Initiate's Sledgehammer",
    "Iron Awl",
    "Iron Bill",
    "Iron Chaser Hammer",
    "Iron Chocobotail Saw",
    "Iron Cross-pein Hammer",
    "Iron Dolabra",
    "Iron Doming Hammer",
    "Iron File",
    "Iron Hatchet",
    "Iron Head Knife",
    "Iron Labrys",
    "Iron Mortar",
    "Iron Ornamental Hammer",
    "Iron Pickaxe",
    "Iron Pliers",
    "Iron Raising Hammer",
    "Iron Scythe",
    "Iron Shortsword",
    "Iron Sledgehammer",
    "Iron Spatha",
    "Iron War Axe",
    "Manganese Arquebus",
    "Manganese Axe",
    "Manganese Raising Hammer",
    "Manganese Round Knife",
    "Manganese Sledgehammer",
    "Manganese Sword",
    "Molybdenum Daggers",
    "Molybdenum Hatchet",
    "Molybdenum Longsword",
    "Molybdenum Lump Hammer",
    "Molybdenum Mortar",
    "Molybdenum Pliers",
    "Molybdenum Sledgehammer",
    "Molybdenum Uchigatana",
    "Mythril Awl",
    "Mythril Bhuj",
    "Mythril Broadsword",
    "Mythril Claws",
    "Mythril Culinary Knife",
    "Mythril Hatchet",
    "Mythril Head Knife",
    "Mythril Mortar",
    "Mythril Ornamental Hammer",
    "Mythril Pliers",
    "Mythril Round Knife",
    "Mythrite Claymore",
    "Mythrite Flametongue",
    "Mythrite Jamadhars",
    "Mythrite Lump Hammer",
    "Mythrite Pickaxe",
    "Mythrite Round Knife",
    "Mythrite Stilettos",
    "Mythrite War Axe",
    "Mythrite-barreled Arquebus",
    "Palladium Texture Hammer",
    "Plumed Bronze Pickaxe",
    "Plumed Doman Steel Pickaxe",
    "Plumed Iron Hatchet",
    "Plumed Mythril Pickaxe",
    "Spiked Bronze Labrys",
    "Spiked Cobalt Labrys",
    "Spiked Knuckles",
    "Spiked Mythril Labrys",
    "Spiked Steel Labrys",
    "Steel Awl",
    "Steel Bardiche",
    "Steel Bhuj",
    "Steel Broadsword",
    "Steel Chaser Hammer",
    "Steel Claw Hammer",
    "Steel Claws",
    "Steel Crowsbeak Hammer",
    "Steel Culinary Knife",
    "Steel Dolabra",
    "Steel Doming Hammer",
    "Steel Falchion",
    "Steel File",
    "Steel Hatchet",
    "Steel Longsword",
    "Steel Mortar",
    "Steel Pickaxe",
    "Steel Pliers",
    "Steel Scythe",
    "Steel Sledgehammer",
    "Titanbronze Bayonet",
    "Titanbronze Creasing Knife",
    "Titanbronze File",
    "Titanbronze Kilij",
    "Titanbronze Sledgehammer",
    "Titanbronze Uchigatana",
    "Titanium Awl",
    "Titanium Axe",
    "Titanium Claymore",
    "Titanium Greatsword",
    "Titanium Hatchet",
    "Titanium Pliers",
    "Titanium Sledgehammer",
    "Titanium-barreled Arquebus",
    "Titanium-barreled Snaphance",
    "Viking Sword",
    "Wrapped Steel Awl",
    "Wrapped Steel Claw Hammer",
    "Wrapped Steel Sledgehammer",
    
    // Carpenter Items
    "Adamantite Spear",
    "Almandine Grinding Wheel",
    "Amateur's Fishing Rod",
    "Amateur's Spinning Wheel",
    "Applewood Cane",
    "Applewood Longbow",
    "Applewood Spear",
    "Applewood Staff",
    "Ash Cavalry Bow",
    "Ash Composite Bow",
    "Ash Macuahuitl",
    "Ash Mask",
    "Ash Mask (Lapis Lazuli)",
    "Ash Pattens",
    "Ash Radical",
    "Ash Shortbow",
    "Ash Spinning Wheel",
    "Astral Grinding Wheel",
    "Basilisk Grinding Wheel",
    "Beech Composite Bow",
    "Birch Composite Bow",
    "Birch Fishing Rod",
    "Birch Longbow",
    "Birch Rod",
    "Birch Signum",
    "Birch Spinning Wheel",
    "Bluespirit Cane",
    "Bone Harpoon",
    "Bronze Spear",
    "Cedar Crook",
    "Cedar Fishing Rod",
    "Cedar Longbow",
    "Cobalt Cavalry Bow",
    "Cobalt Halberd",
    "Cobalt Trident",
    "Crab Bow",
    "Dark Chestnut Fishing Rod",
    "Dark Chestnut Longbow",
    "Dark Chestnut Spinning Wheel",
    "Doman Iron Lance",
    "Dragonscale Grinding Wheel",
    "Dwarven Lignum Bow",
    "Dwarven Lignum Lance",
    "Dwarven Lignum Pole",
    "Eagle-crested Round Shield",
    "Elm Cane",
    "Elm Crook",
    "Elm Fishing Rod",
    "Elm Longbow",
    "Elm Macuahuitl",
    "Elm Pattens",
    "Elm Spinning Wheel",
    "Elm Velocity Bow",
    "Feathered Harpoon",
    "Garnet Grinding Wheel",
    "Gazelle Horn Fishing Rod",
    "Gilded Rosewood Fishing Rod",
    "Hallowed Chestnut Composite Bow",
    "Hallowed Chestnut Fishing Rod",
    "Hallowed Chestnut Mask of Healing",
    "Hallowed Chestnut Necklace",
    "Hallowed Chestnut Ring",
    "Hart Guisarme",
    "Heavy Steel Lance",
    "High Steel Trident",
    "Holy Cedar Armillae",
    "Holy Cedar Composite Bow",
    "Holy Cedar Necklace",
    "Holy Cedar Spinning Wheel",
    "Horn Fishing Rod",
    "Horse Chestnut Cane",
    "Horse Chestnut Fishing Rod",
    "Horse Chestnut Kasa",
    "Initiate's Fishing Rod",
    "Initiate's Grinding Wheel",
    "Initiate's Spinning Wheel",
    "Integral Bracelet of Crafting",
    "Integral Earrings of Crafting",
    "Integral Fishing Rod",
    "Integral Grinding Wheel",
    "Integral Magitek Bow",
    "Integral Magitek Cane",
    "Integral Magitek Spear",
    "Integral Ring of Crafting",
    "Integral Spinning Wheel",
    "Iron Guisarme",
    "Iron Lance",
    "Iron Spear",
    "Ironwood Choker of Aiming",
    "Ironwood Earrings of Crafting",
    "Ironwood Fishing Rod",
    "Ironwood Grinding Wheel",
    "Ironwood Spinning Wheel",
    "Ironwood Staff",
    "Jade Crook",
    "Larch Earrings",
    "Larch Necklace",
    "Larch Ring",
    "Larch Spinning Wheel",
    "Larch Wand",
    "Lignum Vitae Bracelet",
    "Lignum Vitae Fishing Rod",
    "Lignum Vitae Grinding Wheel",
    "Lignum Vitae Necklace",
    "Lignum Vitae Ring",
    "Lignum Vitae Spinning Wheel",
    "Mahogany Fishing Rod",
    "Mahogany Pattens",
    "Mahogany Spinning Wheel",
    "Maple Cane",
    "Maple Clogs",
    "Maple Crook",
    "Maple Fishing Rod",
    "Maple Longbow",
    "Maple Pattens",
    "Maple Shortbow",
    "Molybdenum Trident",
    "Mudstone Grinding Wheel",
    "Muudhorn Fishing Rod",
    "Mythril Cavalry Bow",
    "Mythril Lance",
    "Mythrite Pugil Stick",
    "Mythrite Trident",
    "Oak Composite Bow",
    "Oak Pattens",
    "Oak Radical",
    "Palm Bracelets of Casting",
    "Palm Bracelets of Fending",
    "Palm Bracelets of Slaying",
    "Palm Ear Cuffs of Aiming",
    "Palm Halberd",
    "Palm Longbow",
    "Pastoral Oak Cane",
    "Persimmon Bow",
    "Persimmon Cane",
    "Persimmon Necklace",
    "Persimmon Spinning Wheel",
    "Pine Cane",
    "Pine Composite Bow",
    "Pine Fishing Rod",
    "Pine Spinning Wheel",
    "Plumed Oak Macuahuitl",
    "Plumed Yew Crook",
    "Polished Slate Grinding Wheel",
    "Ragstone Grinding Wheel",
    "Ramhorn Harpoon",
    "Red Pine Cane",
    "Red Pine Fishing Rod",
    "Red Pine Grinding Wheel",
    "Red Pine Spear",
    "Red Pine Spinning Wheel",
    "Rosewood Fishing Rod",
    "Rosewood Spinning Wheel",
    "Round Shield",
    "Sandteak Cane",
    "Sandteak Fauchard",
    "Sandteak Fishing Rod",
    "Sandteak Grinding Wheel",
    "Sandteak Longbow",
    "Sandteak Spinning Wheel",
    "Siltstone Grinding Wheel",
    "Silver Battle Fork",
    "Slate Grinding Wheel",
    "Sprouting Rosewood Radical",
    "Square Ash Shield",
    "Staghorn Fishing Rod",
    "Steel Halberd",
    "Steel Spear",
    "Stiperstone Grinding Wheel",
    "Titanium Lance",
    "Viper-crested Round Shield",
    "Walnut Cane",
    "Walnut Fishing Rod",
    "Walnut Macuahuitl",
    "Walnut Pattens",
    "Walnut Spinning Wheel",
    "White Ash Earring of Fending",
    "White Ash Fishing Rod",
    "White Ash Necklace",
    "White Ash Ring",
    "White Ash Spinning Wheel",
    "White Oak Bracelets",
    "White Oak Earrings",
    "White Oak Ring",
    "Wrapped Elm Longbow",
    "Yarzonshell Harpoon",
    "Yew Crook",
    "Yew Fishing Rod",
    "Yew Longbow",
    "Yew Radical",
    "Zelkova Bracelets",
    "Zelkova Cane",
    "Zelkova Earrings",
    "Zelkova Fishing Rod",
    "Zelkova Longbow",
    "Zelkova Ring",
    "Zelkova Spinning Wheel",
    
    // Culinarian Items
    "Acorn Cookie",
    "Aldgoat Steak",
    "Alligator Salad",
    "Amra Lassi",
    "Amra Salad",
    "Antelope Steak",
    "Antelope Stew",
    "Apple Juice",
    "Apple Tart",
    "Baguette",
    "Baked Alien Soup",
    "Baked Megapiranha",
    "Baked Onion Soup",
    "Baked Pipira Pira",
    "Baked Sole",
    "Baklava",
    "Beef Stew",
    "Blood Bouillabaisse",
    "Blood Currant Tart",
    "Blood Tomato Juice",
    "Blood Tomato Salad",
    "Boiled Amberjack Head",
    "Boiled Bream",
    "Boiled Crayfish",
    "Boiled Egg",
    "Borscht",
    "Bouillabaisse",
    "Braised Pipira",
    "Broad Bean Salad",
    "Bubble Chocolate",
    "Buckwheat Tea",
    "Button Mushroom Saute",
    "Buttons in a Blanket",
    "Caramels",
    "Carrot Nibbles",
    "Cawl Cennin",
    "Chamomile Tea",
    "Chanterelle Saute",
    "Charred Charr",
    "Cheese Risotto",
    "Cheese Souffle",
    "Chicken and Mushrooms",
    "Chirashi-zushi",
    "Clam Chowder",
    "Coconut Cod Chowder",
    "Coffee Biscuit",
    "Cornbread",
    "Cornmeal",
    "Crab Croquette",
    "Crowned Pie",
    "Crumpet",
    "Dark Pretzel",
    "Deviled Eggs",
    "Dhalmel Fricassee",
    "Dhalmel Gratin",
    "Dodo Omelette",
    "Doman Tea",
    "Dried Plums",
    "Dzemael Gratin",
    "Eel Pie",
    "Eft Steak",
    "Egg Foo Young",
    "Emerald Soup",
    "Espresso con Panna",
    "Fig Bavarois",
    "Fish Soup",
    "Fish Stew",
    "Flatbread",
    "Forest Miq'abob",
    "Fried Egg",
    "Frozen Spirits",
    "Frumenty",
    "Gameni",
    "Giant Haddock Dip",
    "Giant Popoto Pancakes",
    "Ginger Cookie",
    "Glory Be Soup",
    "Grape Juice",
    "Grilled Carp",
    "Grilled Dodo",
    "Grilled Platinum Bream",
    "Grilled Raincaller",
    "Grilled Trout",
    "Grilled Turban",
    "Hamsa Curry",
    "Happiness Juice",
    "Hollandaise Sauce",
    "Ishgardian Muffin",
    "Island Miq'abob",
    "Jack-o'-lantern",
    "Jellied Harcot",
    "Jerked Beef",
    "Jerked Jhammel",
    "Jhammel Moussaka",
    "Karniyarik",
    "Kasha",
    "King Crab Cake",
    "Knight's Bread",
    "La Noscean Toast",
    "Lemonade",
    "Lentils and Chestnuts",
    "Liver-cheese Sandwich",
    "Loquat Juice",
    "Marmot Steak",
    "Masala Chai",
    "Mashed Popotoes",
    "Meat Miq'abob",
    "Mint Lassi",
    "Miso Dengaku",
    "Miso Soup with Tofu",
    "Mist Spinach Saute",
    "Mole Loaf",
    "Mugwort Carp",
    "Mulled Tea",
    "Mushroom Saute",
    "Mushroom Skewer",
    "Mustard Eggs",
    "Mutton Stew",
    "Nut Bake",
    "Onigara-yaki",
    "Orange Juice",
    "Orobon Stew",
    "Oysters on the Half Shell",
    "Paella",
    "Parsnip Salad",
    "Pastry Fish",
    "Pea Soup",
    "Pearl Chocolate",
    "Peppered Popotoes",
    "Persimmon Pudding",
    "Philosopher's Sandwich",
    "Pixie Apple Pie",
    "Popoto Soba",
    "Popotoes au Gratin",
    "Purple Carrot Juice",
    "Rabbit Pie",
    "Raptor Stew",
    "Ratatouille",
    "Raw Oyster",
    "Risotto al Nero",
    "Roast Ovim",
    "Roasted Nopales",
    "Royal Eggs",
    "Salmon Meuniere",
    "Salt Cod",
    "Salt Cod Puffs",
    "Sauerkraut",
    "Sauteed Porcini",
    "Scrambled Eggs",
    "Shepherd's Pie",
    "Shorlog",
    "Sideritis Cookie",
    "Smoked Raptor",
    "Spaghetti al Nero",
    "Spicy Shakshouka",
    "Spinach Saute",
    "Steamed Grouper",
    "Steppe Salad",
    "Stewed River Bream",
    "Stone Soup",
    "Stuffed Artichoke",
    "Stuffed Cabbage",
    "Stuffed Cabbage Rolls",
    "Stuffed Chysahl",
    "Sweet and Sour Frogs' Legs",
    "Sykon Bavarois",
    "Sykon Salad",
    "Tempura Platter",
    "Tree Toad Legs",
    "Tsai tou Vounou",
    "Tuna Miq'abob",
    "Ukha",
    "Walnut Bread",
    "Warrior's Stew",
    "Wine-dark Soup",
    "Yakow Moussaka",
    "Zurek",
    
    // Goldsmith Items
    "Amateur's Needle",
    "Amber Bracelet",
    "Amber Ring",
    "Amethyst Earrings",
    "Ametrine Bracelet of Healing",
    "Aquamarine Bracelet",
    "Aquamarine Choker",
    "Aquamarine Earrings",
    "Aurum Regis Bracelet of Aiming",
    "Aurum Regis Circlet of Healing",
    "Aurum Regis Earrings of Healing",
    "Aurum Regis Longpole",
    "Azurite Bracelet of Healing",
    "Azurite Ring of Aiming",
    "Bat Fang Needle",
    "Black Horn Staff",
    "Black Pearl Bracelet",
    "Bladed Steel Jig",
    "Blue Zircon Bracelet of Fending",
    "Blue Zircon Earrings of Casting",
    "Blue Zircon Earrings of Slaying",
    "Blue Zircon Ring of Aiming",
    "Bluespirit Baghnakhs",
    "Bluespirit Glaives",
    "Bluespirit Star Globe",
    "Bone Armillae",
    "Bone Brand",
    "Bone Hora",
    "Bone Necklace",
    "Bone Ring",
    "Bone Staff",
    "Brass Choker",
    "Brass Circlet (Danburite)",
    "Brass Circlet (Fluorite)",
    "Brass Circlet (Lapis Lazuli)",
    "Brass Circlet (Malachite)",
    "Brass Circlet (Sphene)",
    "Brass Circlet (Sunstone)",
    "Brass Cudgel",
    "Brass Ear Cuffs",
    "Brass Earrings",
    "Brass Gorget",
    "Brass Needle",
    "Brass Ring",
    "Brass Ring of Crafting",
    "Brass Spectacles",
    "Brass Wristlets",
    "Brass Wristlets of Crafting",
    "Bronze Scepter",
    "Chondrite Magitek Tuck",
    "Chondrite Magitek Wings",
    "Chondrite Needle",
    "Chrysolite Bracelet of Healing",
    "Citrine Choker of Slaying",
    "Cobalt Preserves",
    "Copper Choker",
    "Copper Ear Cuffs",
    "Copper Earrings",
    "Copper Gorget",
    "Copper Needle",
    "Copper Ring",
    "Copper Scepter",
    "Copper Wristlets",
    "Coral Ring",
    "Crabshell Hora",
    "Danburite Choker",
    "Decorated Bone Staff",
    "Decorated Copper Scepter",
    "Diaspore Bracelet of Aiming",
    "Diaspore Ring of Casting",
    "Diaspore Ring of Fending",
    "Diaspore Ring of Healing",
    "Dragon Fang Earrings",
    "Durium Astrometer",
    "Durium Foil",
    "Durium Hairpin of Fending",
    "Durium Rod",
    "Dwarven Mythril Bracelets",
    "Dwarven Mythril Ear Cuffs",
    "Dwarven Mythril Needle",
    "Dwarven Mythril Rapier",
    "Earth Brand",
    "Electrum Circlet (Rubellite)",
    "Electrum Circlet (Spinel)",
    "Electrum Ear Cuffs",
    "Electrum Earrings",
    "Electrum Ring",
    "Electrum Ring of Crafting",
    "Fang Earrings",
    "Fang Necklace",
    "Fire Brand",
    "Fluorite Bracelet",
    "Fluorite Choker",
    "Garnet Choker",
    "Garnet Ring",
    "Gazelle Horn Needle",
    "Goblin Jig",
    "Goshenite Bracelet",
    "Griffin Talon Ring of Casting",
    "Hardsilver Bangle of Aiming",
    "Hardsilver Earrings of Gathering",
    "Hardsilver Earrings of Slaying",
    "Hardsilver Needle",
    "Hardsilver Planisphere",
    "Hardsilver Staff",
    "Hardsilver Star Globe",
    "Heliodor Earrings",
    "High Durium Planisphere",
    "High Durium Visor of Striking",
    "Horn Armillae",
    "Horn Earrings",
    "Horn Necklace",
    "Horn Ring",
    "Horn Staff",
    "Ice Brand",
    "Imperial Jade Armillae of Casting",
    "Imperial Jade Earrings of Casting",
    "Imperial Jade Necklace of Aiming",
    "Imperial Jade Necklace of Healing",
    "Initiate's Needle",
    "Islewolf Ring of Aiming",
    "Islewolf Ring of Casting",
    "Islewolf Ring of Slaying",
    "Ivory Staff",
    "Jade Scepter",
    "Koppranickel Bracelet of Slaying",
    "Koppranickel Earrings of Aiming",
    "Koppranickel Planisphere",
    "Koppranickel Pole",
    "Koppranickel Rapier",
    "Lapis Lazuli Choker",
    "Lazurite Ring of Fending",
    "Malachite Bracelet",
    "Malachite Choker",
    "Malachite Ring",
    "Manasilver Ear Cuffs",
    "Manasilver Needle",
    "Manganese Horn of the Last Unicorn",
    "Manganese Orrery",
    "Molybdenum Earring of Healing",
    "Mormorion Ring of Fending",
    "Muudhorn Ring of Casting",
    "Muudhorn Ring of Fending",
    "Mythril Circlet (Rubellite)",
    "Mythril Circlet (Spinel)",
    "Mythril Ear Cuffs",
    "Mythril Ring",
    "Mythrite Bangle of Aiming",
    "Mythrite Bracelet of Fending",
    "Mythrite Goggles of Crafting",
    "Mythrite Necklace of Slaying",
    "Mythrite Needle",
    "Obsidian Longpole",
    "Opal Bracelet of Casting",
    "Opal Choker of Fending",
    "Opal Ring of Healing",
    "Palladium Bracelet of Fending",
    "Palladium Ring of Slaying",
    "Palladium Rod",
    "Palladium Tuck",
    "Pearl Bracelet",
    "Pearl Ring",
    "Peridot Choker",
    "Peridot Ring",
    "Petalite Bracelet of Casting",
    "Petalite Bracelet of Healing",
    "Petalite Choker of Fending",
    "Petalite Earrings of Slaying",
    "Petalite Ring of Aiming",
    "Pewter Choker of Aiming",
    "Pewter Choker of Fending",
    "Pewter Choker of Healing",
    "Pewter Circlet of Maiming",
    "Pewter Ring of Casting",
    "Pewter Rod",
    "Phrygian Choker of Healing",
    "Phrygian Ear Cuffs of Aiming",
    "Phrygian Ear Cuffs of Fending",
    "Phrygian Hanger",
    "Phrygian Needle",
    "Phrygian Wings",
    "Ramhorn Claws",
    "Ramhorn Staff",
    "Red Coral Armillae",
    "Red Coral Necklace",
    "Rubellite Bracelet",
    "Silver Choker",
    "Silver Circlet (Amethyst)",
    "Silver Circlet (Aquamarine)",
    "Silver Circlet (Garnet)",
    "Silver Magnifiers",
    "Silver Ring",
    "Silver Ring of Crafting",
    "Silver Spectacles",
    "Sphene Bracelet",
    "Sphene Choker",
    "Sphene Ring",
    "Spinel Bracelet",
    "Spinel Earrings",
    "Spinel Ring",
    "Staghorn Staff",
    "Star Quartz Choker of Healing",
    "Star Quartz Choker of Slaying",
    "Star Quartz Ring of Fending",
    "Star Quartz Wristband of Casting",
    "Star Spinel Bracelet of Aiming",
    "Star Spinel Bracelet of Slaying",
    "Star Spinel Choker of Casting",
    "Star Spinel Earrings of Fending",
    "Star Spinel Ring of Healing",
    "Steel Goggles",
    "Stonegold Orrery",
    "Stonegold Rapier",
    "Sunstone Bracelet",
    "Sunstone Choker",
    "Thousand Needle",
    "Titanbronze Headgear of Maiming",
    "Titanbronze Needle",
    "Titanbronze Rapier",
    "Titanbronze Star Globe",
    "Toothed Goathorn Staff",
    "Toothed Ramhorn Staff",
    "Toothed Staghorn Staff",
    "Tortoiseshell Hora",
    "Tourmaline Choker",
    "Tourmaline Earrings",
    "Triphane Bracelet of Aiming",
    "Triphane Choker of Fending",
    "Triplite Choker of Casting",
    "Triplite Earrings of Healing",
    "Water Brand",
    "Wind Brand",
    "Wolf Earrings",
    "Wolf Necklace",
    "Worm Fang Needle",
    "Yeti Fang Earrings",
    "Yeti Fang Ring of Healing",
    "Yeti Staff",
    "Zircon Choker",
    
    // Leatherworker Items
    "Altered Boarskin Pot Helm",
    "Amateur's Duckbills",
    "Amateur's Headgear",
    "Amateur's Smithing Gloves",
    "Amateur's Thighboots",
    "Archaeoskin Boots of Scouting",
    "Archaeoskin Breeches of Crafting",
    "Archaeoskin Breeches of Maiming",
    "Archaeoskin Gloves of Crafting",
    "Archaeoskin Jackcoat of Gathering",
    "Atrociraptorskin Amulet of Fending",
    "Atrociraptorskin Amulet of Slaying",
    "Atrociraptorskin Breeches of Fending",
    "Atrociraptorskin Corselet of Aiming",
    "Atrociraptorskin Gloves of Gathering",
    "Atrociraptorskin Leg Guards of Scouting",
    "Boarskin Breeches",
    "Boarskin Choker",
    "Boarskin Crakows",
    "Boarskin Crakows of Gathering",
    "Boarskin Culottes",
    "Boarskin Duckbills",
    "Boarskin Himantes",
    "Boarskin Jerkin",
    "Boarskin Pot Helm",
    "Boarskin Ring",
    "Boarskin Ringbands",
    "Boarskin Ringbands of Gales",
    "Boarskin Skirt",
    "Boarskin Smithy's Gloves",
    "Boarskin Subligar",
    "Boarskin Thighboots",
    "Boarskin Workboots",
    "Boarskin Wristbands",
    "Boarskin Wristbands of Gathering",
    "Dhalmelskin Armguards of Scouting",
    "Dhalmelskin Fringe Boots",
    "Dhalmelskin Halfgloves of Crafting",
    "Dhalmelskin Jacket of Striking",
    "Dhalmelskin Leggings of Aiming",
    "Dragonskin Boots of Casting",
    "Dragonskin Breeches of Fending",
    "Dragonskin Breeches of Scouting",
    "Dragonskin Choker",
    "Dragonskin Gloves of Aiming",
    "Dragonskin Gloves of Healing",
    "Fingerless Boarskin Gloves",
    "Fingerless Boarskin Gloves of Gathering",
    "Fingerless Goatskin Gloves",
    "Fingerless Goatskin Gloves of Gathering",
    "Fingerless Hard Leather Gloves",
    "Fingerless Leather Gloves",
    "Fingerless Peisteskin Gloves",
    "Fingerless Raptorskin Gloves of Gathering",
    "Gaganaskin Halfgloves",
    "Gaganaskin Hose of Fending",
    "Gaganaskin Sandals of Scouting",
    "Gajaskin Circlet of Casting",
    "Gajaskin Shoes of Scouting",
    "Gajaskin Vest of Striking",
    "Gazelleskin Armguards of Casting",
    "Gazelleskin Bracers of Healing",
    "Gazelleskin Brais of Striking",
    "Gazelleskin Coat of Fending",
    "Gazelleskin Gloves of Crafting",
    "Gazelleskin Open-toed Boots of Maiming",
    "Gazelleskin Open-toed Boots of Striking",
    "Gazelleskin Ring",
    "Gazelleskin Shoes",
    "Gliderskin Boots of Aiming",
    "Gliderskin Breeches of Maiming",
    "Gliderskin Gloves of Healing",
    "Gliderskin Gloves of Scouting",
    "Gliderskin Gloves of Striking",
    "Gliderskin Thighboots of Fending",
    "Goatskin Armguards",
    "Goatskin Boots",
    "Goatskin Brais",
    "Goatskin Breeches",
    "Goatskin Cesti",
    "Goatskin Choker",
    "Goatskin Crakows",
    "Goatskin Crakows of Gathering",
    "Goatskin Duckbills",
    "Goatskin Espadrilles",
    "Goatskin Eyepatch",
    "Goatskin Leg Guards",
    "Goatskin Leggings",
    "Goatskin Lightmitts",
    "Goatskin Mitts",
    "Goatskin Pot Helm",
    "Goatskin Ring",
    "Goatskin Ringbands",
    "Goatskin Targe",
    "Goatskin Wristbands",
    "Goatskin Wristguards",
    "Gyuki Leather Choker",
    "Gyuki Leather Dress Gloves",
    "Gyuki Leather Highboots of Scouting",
    "Gyuki Leather Jacket",
    "Gyuki Leather Pot Helm",
    "Gyuki Leather Trousers of Fending",
    "Hard Leather Armguards",
    "Hard Leather Boots",
    "Hard Leather Caligae",
    "Hard Leather Choker",
    "Hard Leather Espadrilles",
    "Hard Leather Harness",
    "Hard Leather Lightmitts",
    "Hard Leather Pot Helm",
    "Hard Leather Ringbands",
    "Hard Leather Sandals",
    "Hard Leather Shoes",
    "Hard Leather Skullcap",
    "Hard Leather Subligar",
    "Hard Leather Wristbands of Gathering",
    "Hard Leather Wristguards",
    "Hunting Moccasins",
    "Initiate's Gloves",
    "Initiate's Headgear",
    "Initiate's Thighboots",
    "Kumbhiraskin Gloves of Crafting",
    "Kumbhiraskin Gloves of Gathering",
    "Kumbhiraskin Gloves of the White Griffin",
    "Kumbhiraskin Jacket of the Rising Dragon",
    "Kumbhiraskin Necklace of Gathering",
    "Kumbhiraskin Shoes of Crafting",
    "Leather Boots",
    "Leather Calot",
    "Leather Choker",
    "Leather Crakows",
    "Leather Culottes",
    "Leather Duckbills",
    "Leather Duckbills of Gathering",
    "Leather Eyepatch",
    "Leather Himantes",
    "Leather Jackboots",
    "Leather Jacket",
    "Leather Leggings",
    "Leather Lightmitts",
    "Leather Mitts",
    "Leather Sandals",
    "Leather Shoes",
    "Leather Targe",
    "Leather Wristbands",
    "Leather Wristguards",
    "Luncheon Toadskin Gloves of Striking",
    "Luncheon Toadskin Hose of Fending",
    "Luncheon Toadskin Hose of Scouting",
    "Luncheon Toadskin Jacket of Striking",
    "Luncheon Toadskin Thighboots of Aiming",
    "Luncheon Toadskin Thighboots of Healing",
    "Marid Leather Bolero of Gathering",
    "Marid Leather Boots of Healing",
    "Marid Leather Breeches of Fending",
    "Marid Leather Earrings",
    "Marid Leather Gloves of Casting",
    "Marid Leather Hood of Striking",
    "Ophiotauroskin Boots of Aiming",
    "Ophiotauroskin Boots of Gathering",
    "Ophiotauroskin Boots of Maiming",
    "Ophiotauroskin Boots of Striking",
    "Ophiotauroskin Earrings of Gathering",
    "Ophiotauroskin Halfgloves of Crafting",
    "Ophiotauroskin Halfgloves of Gathering",
    "Ophiotauroskin Top of Casting",
    "Ophiotauroskin Top of Scouting",
    "Oxblood Targe",
    "Padded Leather Duckbills",
    "Padded Leather Duckbills of Gathering",
    "Peisteskin Crakows",
    "Peisteskin Harness",
    "Peisteskin Subligar",
    "Raptorskin Boots",
    "Raptorskin Brais",
    "Raptorskin Choker",
    "Raptorskin Culottes",
    "Raptorskin Jacket",
    "Raptorskin Jerkin",
    "Raptorskin Leg Guards",
    "Raptorskin Pot Helm",
    "Raptorskin Ring",
    "Raptorskin Smithy's Gloves",
    "Raptorskin Subligar",
    "Raptorskin Targe",
    "Raptorskin Thighboots",
    "Raptorskin Workboots",
    "Saigaskin Armguards of Fending",
    "Saigaskin Coat of Maiming",
    "Saigaskin Gloves of Aiming",
    "Saigaskin Gloves of Crafting",
    "Saigaskin Sandals of Gathering",
    "Saigaskin Shoes of Healing",
    "Serpentskin Armguards of Striking",
    "Serpentskin Bootlets of Casting",
    "Serpentskin Boots of Striking",
    "Serpentskin Brais of Scouting",
    "Serpentskin Gloves",
    "Serpentskin Hat of Casting",
    "Serpentskin Thighboots of Healing",
    "Serpentskin Vest",
    "Skull Eyepatch",
    "Smilodonskin Earrings",
    "Smilodonskin Gloves of Scouting",
    "Smilodonskin Leggings of Maiming",
    "Swallowskin Coat",
    "Swallowskin Fingerless Gloves",
    "Swallowskin Gloves of Healing",
    "Swallowskin Gloves of Maiming",
    "Swallowskin Robe of Aiming",
    "Swallowskin Robe of Healing",
    "Swallowskin Shoes",
    "Swallowskin Shoes of Casting",
    "Swallowskin Shoes of Striking",
    "Tigerskin Armguards of Casting",
    "Tigerskin Fingerless Gloves of Gathering",
    "Tigerskin Gloves of Aiming",
    "Tigerskin Gloves of Scouting",
    "Tigerskin Jackboots of Healing",
    "Tigerskin Tricorne of Scouting",
    "Toadskin Armguards",
    "Toadskin Brais",
    "Toadskin Breeches",
    "Toadskin Cesti",
    "Toadskin Culottes",
    "Toadskin Duckbills",
    "Toadskin Jacket",
    "Toadskin Jerkin",
    "Toadskin Leg Guards",
    "Toadskin Ring",
    "Toadskin Workboots",
    "Wyvernskin Boots of Healing",
    "Wyvernskin Culottes",
    "Wyvernskin Gloves of Casting",
    "Wyvernskin Jerkin",
    "Wyvernskin Mane of Fending",
    "Wyvernskin Wristbands",
    "Zonureskin Caligae of Striking",
    "Zonureskin Coat of Fending",
    "Zonureskin Fingerless Gloves of Casting",
    "Zonureskin Fingerless Gloves of Healing",
    "Zonureskin Fingerless Gloves of Maiming",
    "Zonureskin Gloves of Gathering",
    
    // Weaver Items
    "AR-Caean Velvet Bottoms of Aiming",
    "AR-Caean Velvet Bottoms of Maiming",
    "AR-Caean Velvet Cap of Healing",
    "AR-Caean Velvet Culottes of Gathering",
    "AR-Caean Velvet Hat of Casting",
    "AR-Caean Velvet Hat of Scouting",
    "AR-Caean Velvet Top of Striking",
    "AR-Caean Velvet Work Cap of Crafting",
    "AR-Caean Velvet Work Shirt of Crafting",
    "Almasty Serge Coat of Aiming",
    "Almasty Serge Coat of Casting",
    "Almasty Serge Gloves of Healing",
    "Almasty Serge Hat of Healing",
    "Almasty Serge Headband of Scouting",
    "Almasty Serge Headband of Striking",
    "Altered Velveteen Bandana",
    "Amateur's Breeches",
    "Amateur's Dalmatica",
    "Amateur's Hempen Coif",
    "Amateur's Kurta",
    "Amateur's Slops",
    "Angler's Hat",
    "Bloodhempen Chestwrap of Healing",
    "Bloodhempen Trousers of Gathering",
    "Bloodhempen Turban of Crafting",
    "Brightlinen Bottoms of Crafting",
    "Brightlinen Turban of Crafting",
    "Brightlinen Turban of Gathering",
    "Chimerical Felt Alb of Healing",
    "Chimerical Felt Cap of Striking",
    "Chimerical Felt Cyclas of Aiming",
    "Chimerical Felt Gloves of Healing",
    "Chimerical Felt Hat of Casting",
    "Chimerical Felt Hose of Scouting",
    "Chimerical Felt Klobuk of Healing",
    "Chimerical Felt Skirt",
    "Chimerical Felt Tabard of Striking",
    "Cotton Acton",
    "Cotton Coif",
    "Cotton Coif of Gathering",
    "Cotton Dalmatica",
    "Cotton Dalmatica of Gathering",
    "Cotton Doublet Vest of Crafting",
    "Cotton Doublet Vest of Gathering",
    "Cotton Dress Gloves",
    "Cotton Dress Shoes",
    "Cotton Gaskins",
    "Cotton Halfgloves",
    "Cotton Halfrobe",
    "Cotton Kecks",
    "Cotton Kurta",
    "Cotton Sarouel",
    "Cotton Scarf",
    "Cotton Shepherd's Slops",
    "Cotton Shepherd's Tunic",
    "Cotton Shirt",
    "Cotton Sugarloaf Hat",
    "Cotton Tabard",
    "Cotton Tights",
    "Cotton Trousers",
    "Cotton Turban",
    "Cotton Work Gloves",
    "Cropped Twinsilk Slops",
    "Darkhempen Dogi",
    "Darkhempen Skirt of Scouting",
    "Dwarven Cotton Beret",
    "Dwarven Cotton Gaskins of Aiming",
    "Dwarven Cotton Gaskins of Healing",
    "Dwarven Cotton Gaskins of Maiming",
    "Dwarven Cotton Gaskins of Scouting",
    "Dwarven Cotton Jacket",
    "Dwarven Cotton Petasos of Casting",
    "Dwarven Cotton Trousers",
    "Dwarven Cotton Turban of Aiming",
    "Felt Beret",
    "Felt Bliaud",
    "Felt Cavalier's Hat",
    "Felt Chausses",
    "Felt Coif",
    "Felt Dress Gloves",
    "Felt Dress Shoes",
    "Felt Gaskins",
    "Felt Hat",
    "Felt Kecks",
    "Felt Trousers",
    "Felt Work Gloves",
    "Fingerless Darkhempen Gloves of Casting",
    "Hallowed Ramie Doublet of Aiming",
    "Hallowed Ramie Doublet of Casting",
    "Hallowed Ramie Gaskins of Healing",
    "Hempen Acton",
    "Hempen Bandana",
    "Hempen Bottoms",
    "Hempen Bracers",
    "Hempen Breeches",
    "Hempen Breeches of Crafting",
    "Hempen Camise",
    "Hempen Dalmatica of Gathering",
    "Hempen Doublet Vest of Gathering",
    "Hempen Dress Gloves",
    "Hempen Gaskins",
    "Hempen Halfgloves",
    "Hempen Halfrobe",
    "Hempen Kecks",
    "Hempen Kurta",
    "Hempen Pantalettes",
    "Hempen Robe",
    "Hempen Shepherd's Slops",
    "Hempen Shepherd's Tunic",
    "Hempen Shortgloves",
    "Hempen Tabard",
    "Hempen Tunic",
    "Hempen Underpants",
    "Hempen Undershirt",
    "Hempen Work Gloves",
    "Holy Rainbow Hat of Aiming",
    "Holy Rainbow Sarouel of Fending",
    "Holy Rainbow Sarouel of Healing",
    "Holy Rainbow Shirt of Maiming",
    "Holy Rainbow Shirt of Striking",
    "Holy Rainbow Shoes",
    "Holy Rainbow Work Gloves",
    "Initiate's Doublet Vest",
    "Initiate's Slops",
    "Iridescent Bottoms of Aiming",
    "Iridescent Bottoms of Casting",
    "Iridescent Bottoms of Healing",
    "Iridescent Hat of Aiming",
    "Iridescent Hat of Striking",
    "Iridescent Hood of Maiming",
    "Kudzu Coat of Gathering",
    "Kudzu Culottes of Crafting",
    "Kudzu Hat of Casting",
    "Kudzu Hat of Healing",
    "Kudzu Longkilt of Maiming",
    "Kudzu Trousers of Striking",
    "Linen Bottoms",
    "Linen Chausses",
    "Linen Coatee of Crafting",
    "Linen Cowl",
    "Linen Gaiters",
    "Linen Halfgloves",
    "Linen Hat",
    "Linen Robe",
    "Linen Sarouel",
    "Linen Shirt",
    "Linen Shortgloves",
    "Linen Slops",
    "Linen Smock",
    "Linen Tights",
    "Linen Trousers",
    "Linen Turban",
    "Linen Wedge Cap of Crafting",
    "Linen Wedge Cap of Gathering",
    "Ovim Wool Bottoms of Aiming",
    "Ovim Wool Bottoms of Maiming",
    "Ovim Wool Gaskins of Crafting",
    "Ovim Wool Skirt of Healing",
    "Ovim Wool Tunic of Casting",
    "Ovim Wool Turban of Crafting",
    "Padded Cotton Trousers",
    "Padded Hempen Trousers",
    "Padded Linen Trousers",
    "Padded Woolen Trousers",
    "Patrician's Bottoms",
    "Patrician's Coatee",
    "Patrician's Gaiters",
    "Patrician's Gloves",
    "Patrician's Wedge Cap",
    "Pixie Cotton Acton of Striking",
    "Pixie Cotton Brais of Scouting",
    "Pixie Cotton Hat of Crafting",
    "Pixie Cotton Robe of Healing",
    "Pixie Cotton Sleeves of Striking",
    "Pixie Cotton Slops of Gathering",
    "Rainbow Coif of Scouting",
    "Rainbow Culottes of Striking",
    "Rainbow Robe of Casting",
    "Rainmaker's Hat",
    "Ramie Doublet of Crafting",
    "Ramie Halfgloves of Casting",
    "Ramie Ribbon of Fending",
    "Ramie Robe of Healing",
    "Ramie Skirt",
    "Ramie Trousers of Gathering",
    "Ramie Trousers of Scouting",
    "Ramie Turban of Crafting",
    "Ruby Cotton Bandana of Scouting",
    "Ruby Cotton Cap",
    "Ruby Cotton Chasuble",
    "Ruby Cotton Fingerless Gloves of Casting",
    "Ruby Cotton Hat of Casting",
    "Ruby Cotton Sarouel",
    "Scarlet Moko Bottoms of Crafting",
    "Scarlet Moko Gaskins of the Falling Dragon",
    "Scarlet Moko Hood of the Black Griffin",
    "Scarlet Moko Robe of the Last Unicorn",
    "Scarlet Moko Vest of Gathering",
    "Scarlet Moko Wedge Cap of Crafting",
    "Serge Gambison of Aiming",
    "Serge Hat of Aiming",
    "Serge Hat of Casting",
    "Serge Hat of Healing",
    "Serge Hose of Casting",
    "Serge Poncho",
    "Serge Turban of Gathering",
    "Serge Work Gloves",
    "Snow Linen Bottoms of Crafting",
    "Snow Linen Cap of Healing",
    "Snow Linen Cap of Scouting",
    "Snow Linen Coat of Gathering",
    "Snow Linen Sarouel of Casting",
    "Snow Linen Turban of Gathering",
    "Stablehand's Hat",
    "Stablemaid's Hat",
    "Straw Hat",
    "Striped Cotton Slops",
    "Twinsilk Hood of Healing",
    "Twinsilk Hood of Striking",
    "Twinsilk Robe of Aiming",
    "Twinsilk Slops of Aiming",
    "Twinsilk Slops of Fending",
    "Twinsilk Turban of Scouting",
    "Velveteen Bandana",
    "Velveteen Beret",
    "Velveteen Bottoms",
    "Velveteen Chausses",
    "Velveteen Coatee of Crafting",
    "Velveteen Coatee of Gathering",
    "Velveteen Cowl",
    "Velveteen Doublet Vest of Crafting",
    "Velveteen Doublet Vest of Gathering",
    "Velveteen Dress Gloves",
    "Velveteen Gaskins",
    "Velveteen Gloves",
    "Velveteen Gown",
    "Velveteen Halfgloves",
    "Velveteen Sarouel",
    "Velveteen Sarouel of Gathering",
    "Velveteen Shirt",
    "Velveteen Shortgloves",
    "Velveteen Sugarloaf Hat",
    "Velveteen Tights",
    "Velveteen Trousers",
    "Velveteen Turban",
    "Velveteen Wedge Cap of Crafting",
    "Velveteen Wedge Cap of Gathering",
    "Velveteen Work Gloves",
    "Woolen Chausses",
    "Woolen Coif",
    "Woolen Coif of Gathering",
    "Woolen Dress Gloves",
    "Woolen Gown",
    "Woolen Halfgloves",
    "Woolen Hat",
    "Woolen Sarouel",
    "Woolen Slops",
    "Woolen Smock",
    "Woolen Tights",
    "Woolen Trousers",
    "Woolen Turban"
]
