import Foundation
import SwiftUI

/// Strings used throughout the app.
enum AppStrings {
    /// Strings used throughout the app.
    enum General {
        static let about = String(localized: "general.about")
        static let appName = String(localized: "general.appName")
        static let confirm = String(localized: "general.confirm")
        static let description = String(localized: "general.description")
        static let done = String(localized: "general.done")
        static let equipment = String(localized: "general.equipment")
        static let expansion = String(localized: "general.expansion")
        static let expertDelivery = String(localized: "general.expertDelivery")
        static let gathering = String(localized: "general.gathering")
        static let ingredients = String(localized: "general.ingredients")
        static let item = String(localized: "general.item")
        static let items = String(localized: "general.items")
        static let leves = String(localized: "general.leves")
        static let masterRecipe = String(localized: "general.masterRecipe")
        static let quantity = String(localized: "general.quantity")
        static let recipes = String(localized: "general.recipes")
        static let result = String(localized: "general.result")
        static let settings = String(localized: "general.settings")
        static let sort = String(localized: "general.sort")
        static let textAndBoldText = String(localized: "general.textAndBoldText")
        static let yes = String(localized: "general.yes")
    }

    /// Strings used in the info view tab.
    enum Info {
        static let about = String(localized: "info.about")
        static let credits = String(localized: "info.credits")
        static let creditsLodestoneNews = String(localized: "info.creditsLodestoneNews")
        static let creditsLodestoneNewsURL = String(localized: "info.creditsLodestoneNewsURL")
        static let creditsTeamcraft = String(localized: "info.creditsTeamcraft")
        static let creditsTeamcraftURL = String(localized: "info.creditsTeamcraftURL")
        static let databaseVersion = String(localized: "info.databaseVersion")
        static let emailMe = String(localized: "info.emailMe")
        static let emailMeURL = String(localized: "info.emailMeURL")
        static let legal = String(localized: "info.legal")
        static let privacyPolicy = String(localized: "info.privacyPolicy")
        static let privacyPolicyURL = String(localized: "info.privacyPolicyURL")
    }

    /// Strings used on views pertaining to Items.
    enum Item {
        static let allNodes = String(localized: "item.allNodes")
        static let bonuses = String(localized: "item.bonuses")
        static let canBeHQ = String(localized: "item.canBeHQ")
        static let canBeQuickSynthesized = String(localized: "item.canBeQuickSynthesized")
        static let cannotBeHQ = String(localized: "item.cannotBeHQ")
        static let cannotBeQuickSynthesized = String(localized: "item.cannotBeQuickSynthesized")
        static let deleteRecipe = String(localized: "item.deleteRecipe")
        static let grandCompanyQuantity = String(localized: "item.grandCompanyQuantity")
        static let levelAndType = String(localized: "item.levelAndType")
        static let locationAndCoordinates = String(localized: "item.locationAndCoordinates")
        static let noRecipes = String(localized: "item.noRecipes")
        static let seals = String(localized: "item.seals")
        static let stats = String(localized: "item.stats")
        static let xp = String(localized: "item.xp")
    }

    /// Strings referring to Jobs.
    enum Job {
        static let adventurer = String(localized: "job.adventurer")
        static let adventurerAbbv = String(localized: "job.adventurerAbbv")
        static let alchemist = String(localized: "job.alchemist")
        static let alchemistAbbv = String(localized: "job.alchemistAbbv")
        static let arcanist = String(localized: "job.arcanist")
        static let arcanistAbbv = String(localized: "job.arcanistAbbv")
        static let archer = String(localized: "job.archer")
        static let archerAbbv = String(localized: "job.archerAbbv")
        static let armorer = String(localized: "job.armorer")
        static let armorerAbbv = String(localized: "job.armorerAbbv")
        static let astrologian = String(localized: "job.astrologian")
        static let astrologianAbbv = String(localized: "job.astrologianAbbv")
        static let bard = String(localized: "job.bard")
        static let bardAbbv = String(localized: "job.bardAbbv")
        static let blackMage = String(localized: "job.blackMage")
        static let blackMageAbbv = String(localized: "job.blackMageAbbv")
        static let blacksmith = String(localized: "job.blacksmith")
        static let blacksmithAbbv = String(localized: "job.blacksmithAbbv")
        static let botanist = String(localized: "job.botanist")
        static let botanistAbbv = String(localized: "job.botanistAbbv")
        static let blueMage = String(localized: "job.blueMage")
        static let blueMageAbbv = String(localized: "job.blueMageAbbv")
        static let carpenter = String(localized: "job.carpenter")
        static let carpenterAbbv = String(localized: "job.carpenterAbbv")
        static let conjurer = String(localized: "job.conjurer")
        static let conjurerAbbv = String(localized: "job.conjurerAbbv")
        static let culinarian = String(localized: "job.culinarian")
        static let culinarianAbbv = String(localized: "job.culinarianAbbv")
        static let dancer = String(localized: "job.dancer")
        static let dancerAbbv = String(localized: "job.dancerAbbv")
        static let darkKnight = String(localized: "job.darkKnight")
        static let darkKnightAbbv = String(localized: "job.darkKnightAbbv")
        static let dragoon = String(localized: "job.dragoon")
        static let dragoonAbbv = String(localized: "job.dragoonAbbv")
        static let fisher = String(localized: "job.fisher")
        static let fisherAbbv = String(localized: "job.fisherAbbv")
        static let gladiator = String(localized: "job.gladiator")
        static let gladiatorAbbv = String(localized: "job.gladiatorAbbv")
        static let goldsmith = String(localized: "job.goldsmith")
        static let goldsmithAbbv = String(localized: "job.goldsmithAbbv")
        static let gunbreaker = String(localized: "job.gunbreaker")
        static let gunbreakerAbbv = String(localized: "job.gunbreakerAbbv")
        static let lancer = String(localized: "job.lancer")
        static let lancerAbbv = String(localized: "job.lancerAbbv")
        static let leatherworker = String(localized: "job.leatherworker")
        static let leatherworkerAbbv = String(localized: "job.leatherworkerAbbv")
        static let machinist = String(localized: "job.machinist")
        static let machinistAbbv = String(localized: "job.machinistAbbv")
        static let marauder = String(localized: "job.marauder")
        static let marauderAbbv = String(localized: "job.marauderAbbv")
        static let miner = String(localized: "job.miner")
        static let minerAbbv = String(localized: "job.minerAbbv")
        static let monk = String(localized: "job.monk")
        static let monkAbbv = String(localized: "job.monkAbbv")
        static let ninja = String(localized: "job.ninja")
        static let ninjaAbbv = String(localized: "job.ninjaAbbv")
        static let paladin = String(localized: "job.paladin")
        static let paladinAbbv = String(localized: "job.paladinAbbv")
        static let pictomancer = String(localized: "job.pictomancer")
        static let pictomancerAbbv = String(localized: "job.pictomancerAbbv")
        static let pugilist = String(localized: "job.pugilist")
        static let pugilistAbbv = String(localized: "job.pugilistAbbv")
        static let reaper = String(localized: "job.reaper")
        static let reaperAbbv = String(localized: "job.reaperAbbv")
        static let redMage = String(localized: "job.redMage")
        static let redMageAbbv = String(localized: "job.redMageAbbv")
        static let rogue = String(localized: "job.rogue")
        static let rogueAbbv = String(localized: "job.rogueAbbv")
        static let sage = String(localized: "job.sage")
        static let sageAbbv = String(localized: "job.sageAbbv")
        static let samurai = String(localized: "job.samurai")
        static let samuraiAbbv = String(localized: "job.samuraiAbbv")
        static let scholar = String(localized: "job.scholar")
        static let scholarAbbv = String(localized: "job.scholarAbbv")
        static let summoner = String(localized: "job.summoner")
        static let summonerAbbv = String(localized: "job.summonerAbbv")
        static let thaumaturge = String(localized: "job.thaumaturge")
        static let thaumaturgeAbbv = String(localized: "job.thaumaturgeAbbv")
        static let viper = String(localized: "job.viper")
        static let viperAbbv = String(localized: "job.viperAbbv")
        static let warrior = String(localized: "job.warrior")
        static let warriorAbbv = String(localized: "job.warriorAbbv")
        static let weaver = String(localized: "job.weaver")
        static let weaverAbbv = String(localized: "job.weaverAbbv")
        static let whiteMage = String(localized: "job.whiteMage")
        static let whiteMageAbbv = String(localized: "job.whiteMageAbbv")
    }

    /// Strings used in the Lodestone News section of the app.
    enum LodestoneNews {
        static let keepReading = String(localized: "lodestoneNews.keepReading")
        static let openInWebBrowser = String(localized: "lodestoneNews.openInWebBrowser")
        static let share = String(localized: "lodestoneNews.share")
        static let tapToLoad = String(localized: "lodestoneNews.tapToLoad")
        static let tapToRetry = String(localized: "lodestoneNews.tapToRetry")
    }

    /// Strings used for navigation.
    enum Navigation {
        static let about = String(localized: "navigation.about")
        static let allNodes = String(localized: "navigation.allNodes")
        static let credits = String(localized: "navigation.credits")
        static let itemDetail = String(localized: "navigation.itemDetail")
        static let legal = String(localized: "navigation.legal")
        static let lodestoneNews = String(localized: "navigation.lodestoneNews")
        static let recipeDetail = String(localized: "navigation.recipeDetail")
        static let savedRecipes = String(localized: "navigation.savedRecipes")
        static let search = String(localized: "navigation.search")
        static let shoppingList = String(localized: "navigation.shoppingList")
    }

    enum Parameter {
        static let additionalEffect = String(localized: "parameter.additionalEffect")
        static let attackMagicPotency = String(localized: "parameter.attackMagicPotency")
        static let attackPower = String(localized: "parameter.attackPower")
        static let attackSpeed = String(localized: "parameter.attackSpeed")
        static let bindResistance = String(localized: "parameter.bindResistance")
        static let blindResistance = String(localized: "parameter.blindResistance")
        static let blockRate = String(localized: "parameter.blockRate")
        static let blockStrength = String(localized: "parameter.blockStrength")
        static let bluntResistance = String(localized: "parameter.bluntResistance")
        static let control = String(localized: "parameter.control")
        static let cp = String(localized: "parameter.cp")
        static let craftsmanship = String(localized: "parameter.craftsmanship")
        static let criticalHit = String(localized: "parameter.criticalHit")
        static let criticalHitEvasion = String(localized: "parameter.criticalHitEvasion")
        static let criticalHitPower = String(localized: "parameter.criticalHitPower")
        static let criticalHitResilience = String(localized: "parameter.criticalHitResilience")
        static let defense = String(localized: "parameter.defense")
        static let delay = String(localized: "parameter.delay")
        static let desynthesisSkillGain = String(localized: "parameter.desynthesisSkillGain")
        static let determination = String(localized: "parameter.determination")
        static let dexterity = String(localized: "parameter.dexterity")
        static let directHitRate = String(localized: "parameter.directHitRate")
        static let doomResistance = String(localized: "parameter.doomResistance")
        static let durability = String(localized: "parameter.durability")
        static let earthResistance = String(localized: "parameter.earthResistance")
        static let elementalBonus = String(localized: "parameter.elementalBonus")
        static let enhancementMagicPotency = String(localized: "parameter.enhancementMagicPotency")
        static let enmity = String(localized: "parameter.enmity")
        static let enmityReduction = String(localized: "parameter.enmityReduction")
        static let evasion = String(localized: "parameter.evasion")
        static let expBonus = String(localized: "parameter.expBonus")
        static let fireResistance = String(localized: "parameter.fireResistance")
        static let gathering = String(localized: "parameter.gathering")
        static let gp = String(localized: "parameter.gp")
        static let haste = String(localized: "parameter.haste")
        static let healingMagicPotency = String(localized: "parameter.healingMagicPotency")
        static let heavyResistance = String(localized: "parameter.heavyResistance")
        static let hp = String(localized: "parameter.hp")
        static let iceResistance = String(localized: "parameter.iceResistance")
        static let increasedSpiritbondGain = String(localized: "parameter.increasedSpiritbondGain")
        static let intelligence = String(localized: "parameter.intelligence")
        static let lightningResistance = String(localized: "parameter.lightningResistance")
        static let magicDamage = String(localized: "parameter.magicDamage")
        static let magicDefense = String(localized: "parameter.magicDefense")
        static let magicResistance = String(localized: "parameter.magicResistance")
        static let mainAttribute = String(localized: "parameter.mainAttribute")
        static let mind = String(localized: "parameter.mind")
        static let morale = String(localized: "parameter.morale")
        static let mp = String(localized: "parameter.mp")
        static let paralysisResistance = String(localized: "parameter.paralysisResistance")
        static let perception = String(localized: "parameter.perception")
        static let petrificationResistance = String(localized: "parameter.petrificationResistance")
        static let physicalDamage = String(localized: "parameter.physicalDamage")
        static let piercingResistance = String(localized: "parameter.piercingResistance")
        static let piety = String(localized: "parameter.piety")
        static let poisonResistance = String(localized: "parameter.poisonResistance")
        static let progress = String(localized: "parameter.progress")
        static let projectileResistance = String(localized: "parameter.projectileResistance")
        static let quality = String(localized: "parameter.quality")
        static let recipeLevel = String(localized: "parameter.recipeLevel")
        static let reducedDurabilityLoss = String(localized: "parameter.reducedDurabilityLoss")
        static let refresh = String(localized: "parameter.refresh")
        static let regen = String(localized: "parameter.regen")
        static let secondaryAttribute = String(localized: "parameter.secondaryAttribute")
        static let silenceResistance = String(localized: "parameter.silenceResistance")
        static let skillSpeed = String(localized: "parameter.skillSpeed")
        static let slashingResistance = String(localized: "parameter.slashingResistance")
        static let sleepResistance = String(localized: "parameter.sleepResistance")
        static let slowResistance = String(localized: "parameter.slowResistance")
        static let spellSpeed = String(localized: "parameter.spellSpeed")
        static let strength = String(localized: "parameter.strength")
        static let stunResistance = String(localized: "parameter.stunResistance")
        static let tenacity = String(localized: "parameter.tenacity")
        static let tp = String(localized: "parameter.tp")
        static let unknown = String(localized: "parameter.unknown")
        static let vitality = String(localized: "parameter.vitality")
        static let waterResistance = String(localized: "parameter.waterResistance")
        static let windResistance = String(localized: "parameter.windResistance")
        static let yields = String(localized: "parameter.yields")
    }

    /// Strings used on views pertaining to searches.
    enum Search {
        static let ascending = String(localized: "search.ascending")
        static let descending = String(localized: "search.descending")
        static let noResults = String(localized: "search.noResults")
        static let pickerPrompt = String(localized: "search.pickerPrompt")
        static let searchButton = String(localized: "search.searchButton")
        static let searchFieldPrompt = String(localized: "search.searchFieldPrompt")
    }

    /// Strings used in the Shopping List view.
    enum ShoppingList {
        static let baseMaterials = String(localized: "shoppingList.baseMaterials")
    }

    /// Strings used when listing available sort methods.
    enum SortMethod {
        static let alphabetical = String(localized: "sortMethod.alphabetical")
        static let ilvl = String(localized: "sortMethod.ilvl")
        static let patch = String(localized: "sortMethod.patch")
        static let rlvl = String(localized: "sortMethod.rlvl")
    }

    /// Strings used in the tab bar.
    enum TabView {
        static let info = String(localized: "tabView.info")
        static let news = String(localized: "tabView.news")
        static let recipes = String(localized: "tabView.recipes")
        static let search = String(localized: "tabView.search")
    }

    /// Strings used in the User ("Recipes") view.
    enum User {
        static let createShoppingList = String(localized: "user.createShoppingList")
        static let deleteAll = String(localized: "user.deleteAll")
        static let deleteItem = String(localized: "user.deleteItem")
        static let deletionConfirmation = String(localized: "user.deletionConfirmation")
        static let noRecipes = String(localized: "user.noRecipes")
        static let sortMethod = String(localized: "user.sortMethod")
        static let sortOrder = String(localized: "user.sortOrder")
    }
}
